# codemagic.yaml
workflows:
  ios-workflow:
    name: iOS Sideload Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Build iOS IPA
        script: |
          # The --no-codesign flag prevents the need for an Apple Developer Account
          # It will generate an unsigned IPA in the build folder
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
      - build/ios/iphoneos/*.app