# codemagic.yaml
workflows:
  ios-workflow:
    name: iOS IPA Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
        - app_store_credentials # Ensure variables are in this group
      vars:
        BUNDLE_ID: "com.example.act3WeatherApplication" # Update this to your ID
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          # This command handles certificates uploaded to the Codemagic UI
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install Pods
        script: |
          cd ios && pod install
      - name: Flutter build ipa
        script: |
          # The use-profiles command automatically generates the export_options.plist
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - your-email@example.com