# codemagic.yaml
workflows:
  ios-workflow:
    name: iOS IPA Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: "com.example.act3WeatherApplication"
        XCODE_WORKSPACE: "ios/Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          flutter packages pub get
      - name: Install Pods
        script: |
          # This ensures we are in the right folder and the iOS project is ready
          cd ios
          rm -rf Pods
          rm -rf Podfile.lock
          pod install --repo-update
      - name: Flutter build ipa
        script: |
          flutter build ipa --release \
            --export-options-plist=/Users/builder/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa